# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rajin Dangol's Personal Site # ex. I m Chuan
name: Razin Dangol # ex. DONGChuan
email: dangolrajin@gmail.com
location: Kathmandu, Nepal # ex. Nice, France
github_url: https://github.com/RazinDangol # ex. https://github.com/DONGChuan
facebook: https://facebook.com/DaRazinX
website: http://www.rajin.com.np
description: This is my personal space on the web
favicon: favicon.png # Image must be in assets/images

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://razindangol.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true



# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_programming_language_keywords: [Python,C,Javascript]
skill_web_keywords: [HTML,CSS,Javascript,Bootstrap,Django,Flask,Celery,Redis,Jquery]
skill_technologies_keywords: [Git,Photoshop,Dreamweaver]
